# Generated by Django 4.1.1 on 2022-10-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PucNowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.PositiveIntegerField()),
                ('local', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('weekday', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.PositiveIntegerField()),
                ('groupId', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.PositiveIntegerField()),
                ('groupId', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=32767)),
                ('owner', models.CharField(max_length=20)),
                ('dateTimeSent', models.DateTimeField()),
                ('sent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.PositiveIntegerField()),
                ('userId1', models.PositiveIntegerField()),
                ('userId2', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.PositiveIntegerField()),
                ('private', models.BooleanField()),
            ],
        ),
    ]
