# Generated by Django 4.1.1 on 2022-10-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PucNowapp', '0002_event_groupchat_message_privatechat_studygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=40, max_length=40),
            preserve_default=False,
        ),
    ]
