# Generated by Django 4.1.1 on 2022-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PucNowapp', '0003_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(max_length=2),
        ),
    ]
