# Generated by Django 4.1.1 on 2022-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PucNowapp', '0004_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
