# Generated by Django 4.1.2 on 2022-11-21 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PucNowapp', '0005_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='PucNowapp.student')),
                ('users1', models.ManyToManyField(null=True, to='PucNowapp.student')),
            ],
        ),
    ]
